/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bereitschaftspruefung
         * @description Unversioniert und ohne Token erreichbar - Ziel der Orchestrierungsschicht.
         */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attributdefinitionen auflisten
         * @description Ohne requirementType alle Definitionen einschliesslich ausser Kraft gesetzter. Mit requirementType die fuer diesen Typ geltenden aktiven - typbezogene und allgemeine zusammen. Lesen ist nicht auf platform-admin beschraenkt: Das Frontend braucht die Definitionen, um Formulare aufzubauen (§6).
         */
        get: operations["AttributeDefinitionsController_findAll_v1"];
        put?: never;
        /**
         * Attributdefinition anlegen
         * @description Aendert das gueltige Datenmodell und verlangt daher platform-admin.
         */
        post: operations["AttributeDefinitionsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Attributdefinition aendern
         * @description Erzeugt eine neue Version (ADR-0012). key und requirementType sind unveraenderlich - sie bezeichnen die Definition.
         */
        put: operations["AttributeDefinitionsController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionen einer Attributdefinition
         * @description Vollstaendige Historie nach §19.4.
         */
        get: operations["AttributeDefinitionsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anforderungen auflisten
         * @description Ohne asOf der aktuelle Bestand, mit asOf der Zustand zum Stichtag (§19.4).
         */
        get: operations["RequirementsController_findAll_v1"];
        put?: never;
        /** Anforderung anlegen */
        post: operations["RequirementsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Anforderung ueber den fremden Bezeichner aendern
         * @description Adressiert ueber Herkunftssystem und dortigen Bezeichner - interne Kennungen werden ueber die Servicegrenze nicht gereicht (ADR-0010). Teilweise Aenderung: ein nicht genanntes Feld bleibt unveraendert. Legt nicht an; dafuer POST.
         */
        patch: operations["RequirementsController_patchBySource_v1"];
        trace?: never;
    };
    "/v1/requirements/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionshistorie einer Anforderung
         * @description Alle Versionen, aelteste zuerst. Aus dem Vergleich aufeinanderfolgender Versionen ergeben sich alter Wert, neuer Wert und feldgenaue Herkunft (§16).
         */
        get: operations["RequirementsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttributeDefinitionResponse: {
            /** @description Ausser Kraft gesetzte Definitionen bleiben bestehen - bestehende Anforderungen tragen Werte, die nur mit ihnen deutbar sind. */
            active: boolean;
            /** @description Zulaessige Werte bei enum und multi_enum, sonst leer. */
            allowedValues: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue: Record<string, never> | null;
            /** Format: uuid */
            id: string;
            /** @example kostenstelle */
            key: string;
            /** @example Kostenstelle */
            label: string;
            required: boolean;
            /** @description Anforderungstyp, fuer den die Definition gilt. Leer bedeutet: fuer alle. */
            requirementType: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        AttributeDefinitionVersionResponse: {
            /** @description Ausser Kraft gesetzte Definitionen bleiben bestehen - bestehende Anforderungen tragen Werte, die nur mit ihnen deutbar sind. */
            active: boolean;
            /** @description Zulaessige Werte bei enum und multi_enum, sonst leer. */
            allowedValues: string[] | null;
            changeSource: string;
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue: Record<string, never> | null;
            /** Format: uuid */
            id: string;
            /** @example kostenstelle */
            key: string;
            /** @example Kostenstelle */
            label: string;
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            required: boolean;
            /** @description Anforderungstyp, fuer den die Definition gilt. Leer bedeutet: fuer alle. */
            requirementType: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
        CreateAttributeDefinitionDto: {
            /** @description Pflicht bei enum und multi_enum, unzulaessig bei allen anderen Typen. */
            allowedValues?: string[];
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue?: Record<string, never>;
            /**
             * @description Schluessel im Feld dynamicAttributes. Kleinbuchstaben, Ziffern und Unterstrich - der Wert wird zum JSON-Schluessel und zum Formularfeldnamen.
             * @example kostenstelle
             */
            key: string;
            /** @example Kostenstelle */
            label: string;
            /** @default false */
            required: boolean;
            /**
             * @description Ohne Angabe gilt die Definition fuer alle Anforderungstypen.
             * @example bestellung
             */
            requirementType?: string;
        };
        CreateRequirementDto: {
            dynamicAttributes?: {
                [key: string]: unknown;
            };
            /**
             * @description Bezeichner im Herkunftssystem. Zusammen mit sourceSystem eindeutig - eine Wiederholung wird mit 409 abgewiesen (Idempotenz nach §19.1).
             * @example A-4711
             */
            externalId?: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunft der Daten (§19.1). Ohne Angabe: eigene Erfassung.
             * @example sap
             */
            sourceSystem?: string;
            /**
             * @description Kein Vorgabewert: Ein fest verdrahteter Anfangszustand waere eine Workflow-Annahme, und §7 macht Zustaende konfigurierbar. Ab M4 liefert ihn die Workflow-Definition.
             * @example neu
             */
            status: string;
        };
        PatchRequirementDto: {
            /** @description Wird schluesselweise mit dem Bestand zusammengefuehrt. Ein nicht genannter Schluessel bleibt unveraendert; `null` loescht ihn. */
            dynamicAttributes?: {
                [key: string]: unknown;
            };
            owner?: string;
            /** Format: uuid */
            projectId?: string;
            /** @example feature */
            requirementType?: string;
            /** @example in_arbeit */
            status?: string;
        };
        RequirementResponse: {
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** Format: uuid */
            id: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        RequirementVersionResponse: {
            /** @description Client, der die Aenderung ausgefuehrt hat - aus dem Token. */
            changeSource: string;
            /** @description Ausloesende Identitaet. */
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /**
             * Format: date-time
             * @description Leer bei der aktuell gueltigen Version.
             */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
        UpdateAttributeDefinitionDto: {
            /** @description false setzt die Definition ausser Kraft, ohne sie zu loeschen. */
            active: boolean;
            allowedValues?: string[];
            /** @enum {string} */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            defaultValue?: Record<string, never>;
            label: string;
            required: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dienst ist bereit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    AttributeDefinitionsController_findAll_v1: {
        parameters: {
            query?: {
                requirementType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeDefinitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"];
                };
            };
            /** @description Rumpf unvollstaendig oder Werteliste unpassend */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schluessel fuer diesen Anforderungstyp bereits vergeben */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeDefinitionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionVersionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Stichtag. Ohne Angabe der aktuelle Bestand, mit Angabe der Zustand, den das System zu diesem Zeitpunkt kannte (§19.4). */
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bestand */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"][];
                };
            };
            /** @description Unlesbarer Stichtag */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequirementDto"];
            };
        };
        responses: {
            /** @description Angelegte Anforderung */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Rumpf unvollstaendig, unbekannte Felder, sourceSystem nicht in der Registratur (ADR-0017 A4), oder dynamische Attribute genuegen den geltenden Definitionen nicht (§6). Im letzten Fall traegt die Antwort zusaetzlich ein Feld `attributes` mit je einem Eintrag aus `key` und `message` fuer jedes beanstandete Attribut. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description sourceSystem und externalId existieren bereits (Idempotenz nach §19.1) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_patchBySource_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRequirementDto"];
            };
        };
        responses: {
            /** @description Geaenderte Anforderung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Rumpf unzulaessig oder dynamische Attribute ungueltig */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alle Versionen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementVersionResponse"][];
                };
            };
            /** @description Unlesbare Kennung */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
