/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bereitschaftspruefung
         * @description Unversioniert und ohne Token erreichbar - Ziel der Orchestrierungsschicht.
         */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attributdefinitionen auflisten
         * @description Ohne requirementType alle Definitionen einschliesslich ausser Kraft gesetzter. Mit requirementType die fuer diesen Typ geltenden aktiven - typbezogene und allgemeine zusammen. Lesen ist nicht auf platform-admin beschraenkt: Das Frontend braucht die Definitionen, um Formulare aufzubauen (§6).
         */
        get: operations["AttributeDefinitionsController_findAll_v1"];
        put?: never;
        /**
         * Attributdefinition anlegen
         * @description Aendert das gueltige Datenmodell und verlangt daher platform-admin.
         */
        post: operations["AttributeDefinitionsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Attributdefinition aendern
         * @description Erzeugt eine neue Version (ADR-0012). key und requirementType sind unveraenderlich - sie bezeichnen die Definition.
         */
        put: operations["AttributeDefinitionsController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribute-definitions/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionen einer Attributdefinition
         * @description Vollstaendige Historie nach §19.4.
         */
        get: operations["AttributeDefinitionsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mastership-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hoheitsregeln auflisten
         * @description Welche Quellenklasse fuer ein Feld den Vorrang hat (§19.3). Lesen ist nicht auf platform-admin beschraenkt - die Oberflaeche zeigt anhand der Regel, welche Felder von Hand pflegbar sind.
         */
        get: operations["MastershipController_findAll_v1"];
        put?: never;
        /**
         * Hoheitsregel anlegen
         * @description Entscheidet, wessen Schreibvorgang gewinnt, und verlangt platform-admin.
         */
        post: operations["MastershipController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mastership-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Hoheitsregel aendern
         * @description Erzeugt eine neue Version (ADR-0012). `field` ist unveraenderlich.
         */
        put: operations["MastershipController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mastership-rules/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versionen einer Hoheitsregel */
        get: operations["MastershipController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anforderungen auflisten
         * @description Ohne asOf der aktuelle Bestand, mit asOf der Zustand zum Stichtag (§19.4).
         */
        get: operations["RequirementsController_findAll_v1"];
        put?: never;
        /** Anforderung anlegen */
        post: operations["RequirementsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Anforderung ueber den fremden Bezeichner aendern
         * @description Adressiert ueber Herkunftssystem und dortigen Bezeichner - interne Kennungen werden ueber die Servicegrenze nicht gereicht (ADR-0010). Teilweise Aenderung: ein nicht genanntes Feld bleibt unveraendert. Legt nicht an; dafuer POST.
         */
        patch: operations["RequirementsController_patchBySource_v1"];
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}/holds/{field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Feld gegen automatische Uebernahme festhalten
         * @description Ab dann aendert kein automatischer Ladevorgang dieses Feld an diesem Datensatz (§19.3). Die uebrigen Felder bleiben unberuehrt, und ein Import scheitert nicht - er uebernimmt sie und die Abweisung wird verzeichnet.
         */
        put: operations["RequirementsController_setzeFesthaltung_v1"];
        post?: never;
        /**
         * Festhaltung aufheben
         * @description Eigener, ausdruecklicher Vorgang - keine Nebenwirkung einer Aenderung.
         */
        delete: operations["RequirementsController_hebeFesthaltungAuf_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zustand wechseln
         * @description Eigener Vorgang statt eines Feldes im Rumpf (§7, ADR-0022). Genannt wird der Zielzustand; den passenden Uebergang ermittelt der Dienst. Bei fremdgefuehrten Workflows wird der Zustand entgegengenommen, ohne einen Uebergang zu verlangen - dort fuehrt das Fremdsystem (ADR-0021). Derselbe Zustand erneut zu senden aendert nichts und erzeugt keine Version (§19.1).
         */
        put: operations["RequirementsController_wechsleZustand_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}/state/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zustand zuordnen
         * @description Fuer Anforderungen, deren aktueller Zustand im geltenden Workflow nicht vorkommt - weil sie aelter sind als er, weil ein Import einen fremden Status geliefert hat oder weil ein Zustand entfernt wurde (ADR-0022 Punkt 5). **Kein Uebergang**: Es wird nicht geprueft, ob einer hinfuehrt, und die Historie weist den Vorgang als Zuordnung aus. Die Begruendung ist Pflicht.
         */
        put: operations["RequirementsController_ordneZustandZu_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zulaessige Uebergaenge dieser Anforderung
         * @description Grundlage fuer Schaltflaechen statt eines freien Statusfeldes (§7). Liefert alle Uebergaenge aus dem aktuellen Zustand - **auch die gesperrten, mit Begruendung**, damit die Oberflaeche sagen kann, warum etwas nicht geht. **Die Antwort haengt vom Anmeldenden ab** und darf nicht zwischengespeichert werden.
         */
        get: operations["RequirementsController_zulaessigeUebergaenge_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/by-source/{sourceSystem}/{externalId}/workflow-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Auf die aktuelle Workflow-Fassung heben
         * @description Laufende Anforderungen bleiben auf ihrer Ursprungsfassung (§7). Ist eine Definition fachlich falsch, erreicht die Berichtigung sie sonst nie - dafuer dieser Vorgang (ADR-0025). Ziel ist immer die aktuelle Fassung; der Zustand bleibt unveraendert. Steht die Anforderung bereits auf der aktuellen Fassung, geschieht nichts.
         */
        put: operations["RequirementsController_hebeFassung_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle festgehaltenen Felder
         * @description Plattformweite Uebersicht nach §19.3. Zeigt je Feld den festgehaltenen Wert, die Begruendung und die zuletzt abgewiesene Lieferung samt Anzahl - die Abweichung wird damit beziffert und nicht nur benannt.
         */
        get: operations["RequirementsController_findFesthaltungen_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zustand wechseln, ueber die interne Kennung
         * @description Gleichwertig zum Weg ueber die Herkunft - **derselbe Pruefpfad**, nur ein anderer Zugang. Notwendig fuer eigene Erfassung, deren `externalId` leer ist.
         */
        put: operations["RequirementsController_wechsleZustandUeberKennung_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/state/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zustand zuordnen, ueber die interne Kennung
         * @description Gleichwertig zum Weg ueber die Herkunft. Notwendig fuer eigene Erfassung, deren `externalId` leer ist (§19.1) - und gerade dort haengt eine Anforderung, deren Zustand der Graph nicht kennt.
         */
        put: operations["RequirementsController_ordneZustandZuUeberKennung_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zulaessige Uebergaenge ueber die interne Kennung
         * @description Gleichwertig zum Weg ueber die Herkunft. Notwendig fuer eigene Erfassung: Dort ist `externalId` leer (§19.1), und der Datensatz ist ueber `by-source` nicht adressierbar.
         */
        get: operations["RequirementsController_uebergaengeUeberKennung_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionshistorie einer Anforderung
         * @description Alle Versionen, aelteste zuerst. Aus dem Vergleich aufeinanderfolgender Versionen ergeben sich alter Wert, neuer Wert und feldgenaue Herkunft (§16).
         */
        get: operations["RequirementsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/workflow-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Auf die aktuelle Workflow-Fassung heben, ueber die interne Kennung
         * @description Gleichwertig zum Weg ueber die Herkunft (ADR-0025). Steht die Anforderung bereits auf der aktuellen Fassung, geschieht nichts.
         */
        put: operations["RequirementsController_hebeFassungUeberKennung_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow-Definitionen auflisten
         * @description Einschliesslich ausser Kraft gesetzter und **einschliesslich der Bedingungen** - damit beschreibt die Antwort, wer was freigeben darf, und ist deshalb auf platform-admin beschraenkt. Was ein Erfasser braucht, liefert `GET /v1/requirements/{id}/transitions`: die zulaessigen Uebergaenge seiner Anforderung samt Grund fuer die gesperrten.
         */
        get: operations["WorkflowsController_findAll_v1"];
        put?: never;
        /**
         * Workflow-Definition anlegen
         * @description Legt den gueltigen Ablauf fest und verlangt daher platform-admin.
         */
        post: operations["WorkflowsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Workflow-Definition aendern
         * @description Erzeugt eine neue Version (ADR-0012). requirementType ist unveraenderlich - er bezeichnet, wofuer der Workflow gilt.
         */
        put: operations["WorkflowsController_update_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Welche Fassungen in Gebrauch sind
         * @description Anforderungen je Fassung. Laufende bleiben auf ihrer Ursprungsfassung (§7) - hier wird sichtbar, wie viele davon eine Berichtigung nicht erreicht und wo ein Heben zu erwaegen ist (ADR-0025). Leere Liste, wenn keine Anforderung darauf laeuft.
         */
        get: operations["WorkflowsController_fassungsnutzung_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-definitions/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionen einer Workflow-Definition
         * @description Vollstaendige Historie nach §19.4. Zugleich der Lesepfad fuer §7: Eine laufende Anforderung bleibt auf ihrer Ursprungsfassung, und die steht hier.
         */
        get: operations["WorkflowsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AbgewieseneLieferung: {
            /**
             * @description Wie oft eine Uebernahme dieses Feldes bisher abgewiesen wurde.
             * @example 47
             */
            count: number;
            /** Format: date-time */
            occurredAt: string;
            /** @example sap */
            sourceSystem: string;
            /** @description Der zuletzt abgewiesene Wert. */
            value: Record<string, never>;
        };
        AttributeDefinitionResponse: {
            /** @description Ausser Kraft gesetzte Definitionen bleiben bestehen - bestehende Anforderungen tragen Werte, die nur mit ihnen deutbar sind. */
            active: boolean;
            /** @description Zulaessige Werte bei enum und multi_enum, sonst leer. */
            allowedValues: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue: string | number | boolean | string[] | null;
            /** Format: uuid */
            id: string;
            /** @example kostenstelle */
            key: string;
            /** @example Kostenstelle */
            label: string;
            required: boolean;
            /** @description Anforderungstyp, fuer den die Definition gilt. Leer bedeutet: fuer alle. */
            requirementType: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        AttributeDefinitionVersionResponse: {
            /** @description Ausser Kraft gesetzte Definitionen bleiben bestehen - bestehende Anforderungen tragen Werte, die nur mit ihnen deutbar sind. */
            active: boolean;
            /** @description Zulaessige Werte bei enum und multi_enum, sonst leer. */
            allowedValues: string[] | null;
            changeSource: string;
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue: string | number | boolean | string[] | null;
            /** Format: uuid */
            id: string;
            /** @example kostenstelle */
            key: string;
            /** @example Kostenstelle */
            label: string;
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            required: boolean;
            /** @description Anforderungstyp, fuer den die Definition gilt. Leer bedeutet: fuer alle. */
            requirementType: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
        BedingungsverstossResponse: {
            /**
             * @example vier_augen
             * @enum {string}
             */
            kind: "rolle" | "vier_augen" | "identitaet" | "pflichtfelder" | "feldwert" | "begruendung";
            /**
             * @description Fuer Menschen. Nicht zum Auswerten - der Wortlaut kann sich aendern.
             * @example Dieser Uebergang verlangt eine andere Person als die, die "in_pruefung" ausgeloest hat
             */
            message: string;
        };
        CreateAttributeDefinitionDto: {
            /** @description Pflicht bei enum und multi_enum, unzulaessig bei allen anderen Typen. */
            allowedValues?: string[];
            /**
             * @example text
             * @enum {string}
             */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue?: string | number | boolean | string[] | null;
            /**
             * @description Schluessel im Feld dynamicAttributes. Kleinbuchstaben, Ziffern und Unterstrich - der Wert wird zum JSON-Schluessel und zum Formularfeldnamen.
             * @example kostenstelle
             */
            key: string;
            /** @example Kostenstelle */
            label: string;
            /** @default false */
            required: boolean;
            /**
             * @description Ohne Angabe gilt die Definition fuer alle Anforderungstypen.
             * @example bestellung
             */
            requirementType?: string;
        };
        CreateMastershipRuleDto: {
            /** @example owner */
            field: string;
            /** @enum {string} */
            mode: "manual_allowed" | "automatic_wins" | "manual_locked";
        };
        CreateRequirementDto: {
            dynamicAttributes?: {
                [key: string]: unknown;
            };
            /**
             * @description Bezeichner im Herkunftssystem. Zusammen mit sourceSystem eindeutig - eine Wiederholung wird mit 409 abgewiesen (Idempotenz nach §19.1).
             * @example A-4711
             */
            externalId?: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunft der Daten (§19.1). Ohne Angabe: eigene Erfassung.
             * @example sap
             */
            sourceSystem?: string;
        };
        CreateWorkflowDefinitionDto: {
            /** @example neu */
            initialState: string;
            /** @example Standardablauf */
            label: string;
            /**
             * @default internal
             * @enum {string}
             */
            mode: "internal" | "external";
            /**
             * @description Ohne Angabe gilt der Workflow fuer alle Typen ohne eigenen.
             * @example bestellung
             */
            requirementType?: string;
            states: components["schemas"]["WorkflowStateDto"][];
            transitions: components["schemas"]["WorkflowTransitionDto"][];
        };
        FesthaltungUebersicht: {
            /** @example A-4711 */
            externalId: string | null;
            /** @example owner */
            field: string;
            heldBy: string;
            /** Format: date-time */
            heldSince: string;
            /** @description Der festgehaltene Wert. */
            heldValue: Record<string, never>;
            /** @description Leer, solange kein automatischer Lauf dieses Feld aendern wollte. */
            lastRejection: (components["schemas"]["AbgewieseneLieferung"] | null) & components["schemas"]["AbgewieseneLieferung"];
            reason: string;
            /** Format: uuid */
            requirementId: string;
            /** @example sap */
            sourceSystem: string;
        };
        HebeFassungDto: {
            /** @example Freigaberolle in Fassung 2 war falsch gesetzt, mit Fassung 3 berichtigt */
            reason: string;
        };
        MastershipRuleResponse: {
            /** @description Geltungsbereich nach ADR-0017 A6. Vorerst immer leer - eine Regel gilt fuer alle Anforderungen. */
            bindings: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Kernfeld oder Schluessel eines dynamischen Attributs.
             * @example owner
             */
            field: string;
            /** Format: uuid */
            id: string;
            /**
             * @description manual_allowed: jede berechtigte Quelle schreibt, die letzte gewinnt. automatic_wins: manuelle Aenderung wird abgewiesen, solange eine automatische Quelle das Feld bespielt. manual_locked: manuelle Aenderung ist immer verboten.
             * @example automatic_wins
             * @enum {string}
             */
            mode: "manual_allowed" | "automatic_wins" | "manual_locked";
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        MastershipRuleVersionResponse: {
            /** @description Geltungsbereich nach ADR-0017 A6. Vorerst immer leer - eine Regel gilt fuer alle Anforderungen. */
            bindings: {
                [key: string]: string;
            };
            changeSource: string;
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Kernfeld oder Schluessel eines dynamischen Attributs.
             * @example owner
             */
            field: string;
            /** Format: uuid */
            id: string;
            /**
             * @description manual_allowed: jede berechtigte Quelle schreibt, die letzte gewinnt. automatic_wins: manuelle Aenderung wird abgewiesen, solange eine automatische Quelle das Feld bespielt. manual_locked: manuelle Aenderung ist immer verboten.
             * @example automatic_wins
             * @enum {string}
             */
            mode: "manual_allowed" | "automatic_wins" | "manual_locked";
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
        OrdneZustandZuDto: {
            /** @example Bestand aus der Altablage, Zustand 'Freigegeben' entspricht 'in_pruefung' */
            reason: string;
            /** @example in_pruefung */
            state: string;
        };
        PatchRequirementDto: {
            /** @description Wird schluesselweise mit dem Bestand zusammengefuehrt. Ein nicht genannter Schluessel bleibt unveraendert; `null` loescht ihn. */
            dynamicAttributes?: {
                [key: string]: unknown;
            };
            owner?: string;
            /** Format: uuid */
            projectId?: string;
            /** @example feature */
            requirementType?: string;
        };
        RequirementResponse: {
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** @description Felder, die gegen automatische Uebernahme festgehalten sind (§19.3). Schluessel ist der Feldname, Wert traegt `by`, `at` und `reason`. */
            heldFields: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            id: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
            /** @description Workflow und Fassung, gegen die Zustandswechsel geprueft werden. */
            workflow: components["schemas"]["RequirementWorkflowResponse"];
        };
        RequirementVersionResponse: {
            /** @description Client, der die Aenderung ausgefuehrt hat - aus dem Token. */
            changeSource: string;
            /** @description Ausloesende Identitaet. */
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** @description Felder, die gegen automatische Uebernahme festgehalten sind (§19.3). Schluessel ist der Feldname, Wert traegt `by`, `at` und `reason`. */
            heldFields: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /**
             * Format: date-time
             * @description Leer bei der aktuell gueltigen Version.
             */
            validTo: string | null;
            /** @example 1 */
            version: number;
            /** @description Workflow und Fassung, gegen die Zustandswechsel geprueft werden. */
            workflow: components["schemas"]["RequirementWorkflowResponse"];
        };
        RequirementWorkflowResponse: {
            /** Format: uuid */
            id: string;
            /**
             * @description Fassung, unter der diese Anforderung laeuft - nicht zwingend die aktuelle. Eine Aenderung der Definition wirkt nicht rueckwirkend (§7).
             * @example 1
             */
            version: number;
        };
        SetzeFesthaltungDto: {
            /** @example Von SAP falsch gepflegt, Korrektur dort beantragt unter TICKET-4711 */
            reason: string;
        };
        UebergangsauskunftResponse: {
            /** @example in_pruefung */
            currentState: string;
            /** @description Ob der aktuelle Zustand im geltenden Graphen vorkommt. Bei `false` ist kein Uebergang moeglich, bis ein Administrator ihn zuordnet (ADR-0022 Punkt 5) - die Anforderung ist dann nicht fertig, sondern haengt. */
            currentStateInWorkflow: boolean;
            /** @description Alle Zustaende der gebundenen Fassung - die Auswahl fuer die Zuordnung, wenn der aktuelle Zustand nicht darin vorkommt (ADR-0022 Punkt 5). Immer gefuellt, gerade auch dann, wenn `transitions` leer ist. */
            states: components["schemas"]["WorkflowZustandResponse"][];
            /** @description Alle Uebergaenge aus dem aktuellen Zustand, zulaessige wie gesperrte. Bei fremdgefuehrten Workflows leer: Dort entscheidet das Fremdsystem (ADR-0021). */
            transitions: components["schemas"]["UebergangsoptionResponse"][];
        };
        UebergangsoptionResponse: {
            /** @description Ob dieser Uebergang jetzt und von diesem Anwender genommen werden kann. */
            allowed: boolean;
            /** @description Leer, wenn zulaessig. Sonst jeder Grund einzeln, damit die Oberflaeche alle nennen kann. */
            blockedBy: components["schemas"]["BedingungsverstossResponse"][];
            /** @example Einreichen */
            label: string;
            /** @description Der Uebergang verlangt eine Begruendung. **Kein Hinderungsgrund** - sie wird beim Ausloesen mitgegeben, nicht vorher erfuellt. Deshalb zaehlt sie nicht in `blockedBy`. */
            requiresReason: boolean;
            /** @example in_pruefung */
            toState: string;
        };
        UpdateAttributeDefinitionDto: {
            /** @description false setzt die Definition ausser Kraft, ohne sie zu loeschen. */
            active: boolean;
            allowedValues?: string[];
            /** @enum {string} */
            dataType: "text" | "number" | "boolean" | "date" | "enum" | "multi_enum";
            /** @description Vorgabewert, dem Datentyp entsprechend. */
            defaultValue?: string | number | boolean | string[] | null;
            label: string;
            required: boolean;
        };
        UpdateMastershipRuleDto: {
            /** @enum {string} */
            mode: "manual_allowed" | "automatic_wins" | "manual_locked";
        };
        UpdateWorkflowDefinitionDto: {
            /** @description false setzt den Workflow ausser Kraft, ohne ihn zu loeschen. */
            active: boolean;
            initialState: string;
            label: string;
            /** @enum {string} */
            mode: "internal" | "external";
            states: components["schemas"]["WorkflowStateDto"][];
            transitions: components["schemas"]["WorkflowTransitionDto"][];
        };
        VergleichDto: {
            /** @example kostenschaetzung */
            feld: string;
            /**
             * @example mindestens
             * @enum {string}
             */
            operator: "istGleich" | "istUngleich" | "mindestens" | "hoechstens" | "istEinesVon" | "istGefuellt";
            /** @description istEinesVon erwartet eine Liste, istGefuellt einen Wahrheitswert. */
            wert: string | number | boolean | unknown[] | null;
        };
        WechsleZustandDto: {
            /**
             * @description Pflicht, wenn der Uebergang eine Begruendung verlangt (ADR-0024). Sie wird als Bestandteil der Version festgehalten, nicht als Kommentar daneben.
             * @example Budget durch die Bereichsleitung bestaetigt
             */
            reason?: string;
            /**
             * @description Schluessel des Zielzustands aus dem geltenden Workflow.
             * @example in_pruefung
             */
            toState: string;
        };
        WorkflowBedingungDto: {
            /** @description Bei art=vier_augen: Schluessel des Zustands. */
            andersAlsBeiEintritt?: string;
            /** @enum {string} */
            art: "rolle" | "vier_augen" | "identitaet" | "pflichtfelder" | "feldwert" | "begruendung";
            /** @description Bei art=rolle: eine davon genuegt. */
            eineVon?: string[];
            /** @description Bei art=identitaet und art=feldwert. */
            feld?: string;
            /** @description Bei art=pflichtfelder. */
            felder?: string[];
            /** @description Bei art=begruendung. */
            mindestlaenge?: number;
            /** @description Vorbehalt - alle Vergleiche muessen gelten, damit die Bedingung greift. */
            nurWenn?: components["schemas"]["VergleichDto"][];
            /**
             * @description Bei art=feldwert.
             * @enum {string}
             */
            operator?: "istGleich" | "istUngleich" | "mindestens" | "hoechstens" | "istEinesVon" | "istGefuellt";
            /** @description Bei art=feldwert der Vergleichswert. */
            wert?: string | number | boolean | unknown[] | null;
        };
        WorkflowDefinitionResponse: {
            /** @description false setzt den Workflow ausser Kraft, ohne ihn zu loeschen. */
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** @example neu */
            initialState: string;
            /** @example Standardablauf */
            label: string;
            /**
             * @description internal: Uebergaenge werden hier geprueft und abgewiesen. external: Ein Fremdsystem fuehrt den Vorgang, der Graph beschreibt ihn nur (ADR-0021).
             * @enum {string}
             */
            mode: "internal" | "external";
            /** @description Anforderungstyp, fuer den der Workflow gilt. Leer bedeutet: fuer alle uebrigen. */
            requirementType: string | null;
            states: components["schemas"]["WorkflowStateResponse"][];
            transitions: components["schemas"]["WorkflowTransitionResponse"][];
            /** @description Zustaende, die vom Anfangszustand aus nicht erreichbar sind. Kein Fehler - ein Graph im Aufbau ist unvollstaendig, nicht falsch -, aber ein Hinweis fuer die Verwaltungsoberflaeche. */
            unreachableStates: string[];
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        WorkflowDefinitionVersionResponse: {
            /** @description false setzt den Workflow ausser Kraft, ohne ihn zu loeschen. */
            active: boolean;
            changeSource: string;
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** @example neu */
            initialState: string;
            /** @example Standardablauf */
            label: string;
            /**
             * @description internal: Uebergaenge werden hier geprueft und abgewiesen. external: Ein Fremdsystem fuehrt den Vorgang, der Graph beschreibt ihn nur (ADR-0021).
             * @enum {string}
             */
            mode: "internal" | "external";
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            /** @description Anforderungstyp, fuer den der Workflow gilt. Leer bedeutet: fuer alle uebrigen. */
            requirementType: string | null;
            states: components["schemas"]["WorkflowStateResponse"][];
            transitions: components["schemas"]["WorkflowTransitionResponse"][];
            /** @description Zustaende, die vom Anfangszustand aus nicht erreichbar sind. Kein Fehler - ein Graph im Aufbau ist unvollstaendig, nicht falsch -, aber ein Hinweis fuer die Verwaltungsoberflaeche. */
            unreachableStates: string[];
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
        WorkflowStateDto: {
            /**
             * @description Endzustand - von hier fuehrt kein Uebergang weiter.
             * @default false
             */
            final: boolean;
            /** @example in_pruefung */
            key: string;
            /** @example In Pruefung */
            label: string;
        };
        WorkflowStateResponse: {
            final: boolean;
            /** @example in_pruefung */
            key: string;
            /** @example In Pruefung */
            label: string;
        };
        WorkflowTransitionDto: {
            /** @description Alle muessen erfuellt sein. Ohne Angabe gibt es keine (ADR-0024). */
            bedingungen?: components["schemas"]["WorkflowBedingungDto"][];
            /** @example neu */
            from: string;
            /** @example Einreichen */
            label: string;
            /** @example in_pruefung */
            to: string;
        };
        WorkflowTransitionResponse: {
            /** @description Bedingungen an diesem Uebergang (ADR-0024). Leer, wenn es keine gibt. Nur fuer platform-admin lesbar - sie beschreiben, wer was freigeben darf. */
            bedingungen: components["schemas"]["WorkflowBedingungDto"][];
            from: string;
            label: string;
            to: string;
        };
        WorkflowVersionUsageResponse: {
            /** @description Ob dies die aktuelle Fassung ist. Alles andere laeuft auf einer aelteren - gewollt nach §7, aber der Ort, an dem ein Heben zu erwaegen ist (ADR-0025). */
            current: boolean;
            /**
             * @description Anforderungen auf dieser Fassung.
             * @example 17
             */
            requirements: number;
            /** @example 2 */
            version: number;
        };
        WorkflowZustandResponse: {
            /** @example in_pruefung */
            key: string;
            /** @example In Pruefung */
            label: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dienst ist bereit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    AttributeDefinitionsController_findAll_v1: {
        parameters: {
            query?: {
                requirementType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttributeDefinitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"];
                };
            };
            /** @description Rumpf unvollstaendig oder Werteliste unpassend */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schluessel fuer diesen Anforderungstyp bereits vergeben */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttributeDefinitionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttributeDefinitionsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeDefinitionVersionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MastershipController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MastershipRuleResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MastershipController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMastershipRuleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MastershipRuleResponse"];
                };
            };
            /** @description Feld ist weder Kernfeld noch definiertes Attribut */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fuer dieses Feld besteht bereits eine Regel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MastershipController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMastershipRuleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MastershipRuleResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Regel existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MastershipController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MastershipRuleVersionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Regel existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Stichtag. Ohne Angabe der aktuelle Bestand, mit Angabe der Zustand, den das System zu diesem Zeitpunkt kannte (§19.4). */
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bestand */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"][];
                };
            };
            /** @description Unlesbarer Stichtag */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequirementDto"];
            };
        };
        responses: {
            /** @description Angelegte Anforderung */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Rumpf unvollstaendig, unbekannte Felder, sourceSystem nicht in der Registratur (ADR-0017 A4), oder dynamische Attribute genuegen den geltenden Definitionen nicht (§6). Im letzten Fall traegt die Antwort zusaetzlich ein Feld `attributes` mit je einem Eintrag aus `key` und `message` fuer jedes beanstandete Attribut. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Zwei Ursachen. Entweder sind sourceSystem und externalId bereits vergeben (Idempotenz nach §19.1), oder fuer mindestens ein Feld ist eine andere Quelle massgeblich (§19.3). Im zweiten Fall traegt die Antwort ein Feld `fields` mit je einem Eintrag aus `field`, `reason` und `message`; im ersten fehlt es. Gespeichert wird in beiden Faellen nichts. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_patchBySource_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRequirementDto"];
            };
        };
        responses: {
            /** @description Geaenderte Anforderung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Rumpf unzulaessig oder dynamische Attribute ungueltig */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fuer mindestens ein Feld ist eine andere Quelle massgeblich (§19.3). Die Antwort traegt ein Feld `fields` mit je einem Eintrag aus `field`, `reason` und `message`. Es wird nichts gespeichert - auch nicht die zulaessigen Felder (ADR-0019 Punkt 1). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_setzeFesthaltung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetzeFesthaltungDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Feld ist weder Kernfeld noch definiertes Attribut */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_hebeFesthaltungAuf_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz oder Festhaltung existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_wechsleZustand_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechsleZustandDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Der Zielzustand kommt im geltenden Workflow nicht vor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vier Ursachen. Es gibt keinen Uebergang vom aktuellen in den gewuenschten Zustand; der aktuelle Zustand kommt im geltenden Workflow gar nicht vor und muss zuerst zugeordnet werden; die Bedingungen des Uebergangs sind nicht erfuellt, dann traegt die Antwort ein Feld `conditions`; oder fuer `status` ist eine andere Quelle massgeblich (§19.3), dann traegt sie ein Feld `fields`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_ordneZustandZu_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdneZustandZuDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Der Zustand kommt im geltenden Workflow nicht vor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_zulaessigeUebergaenge_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UebergangsauskunftResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_hebeFassung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceSystem: string;
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HebeFassungDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Datensatz unter dieser Herkunft */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der aktuelle Zustand kommt in der Zielfassung nicht vor - erst zuordnen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findFesthaltungen_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FesthaltungUebersicht"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_wechsleZustandUeberKennung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechsleZustandDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Der Zielzustand kommt im Workflow nicht vor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anforderung existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wie beim Weg ueber die Herkunft: kein Uebergang, unbekannter Ausgangszustand, unerfuellte Bedingungen oder fremde Hoheit */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_ordneZustandZuUeberKennung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdneZustandZuDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Der Zustand kommt im geltenden Workflow nicht vor */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anforderung existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_uebergaengeUeberKennung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UebergangsauskunftResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anforderung existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alle Versionen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementVersionResponse"][];
                };
            };
            /** @description Unlesbare Kennung */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_hebeFassungUeberKennung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HebeFassungDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anforderung existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der aktuelle Zustand fehlt in der Zielfassung */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowDefinitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"];
                };
            };
            /** @description Rumpf unvollstaendig oder Graph widerspruechlich */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fuer diesen Anforderungstyp gibt es bereits einen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkflowDefinitionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"];
                };
            };
            /** @description Rumpf unvollstaendig oder Graph widerspruechlich */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_fassungsnutzung_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersionUsageResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkflowsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionVersionResponse"][];
                };
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rolle platform-admin fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Definition existiert nicht */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
