/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bereitschaftspruefung
         * @description Unversioniert und ohne Token erreichbar - Ziel der Orchestrierungsschicht.
         */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Anforderungen auflisten
         * @description Ohne asOf der aktuelle Bestand, mit asOf der Zustand zum Stichtag (§19.4).
         */
        get: operations["RequirementsController_findAll_v1"];
        put?: never;
        /** Anforderung anlegen */
        post: operations["RequirementsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/requirements/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versionshistorie einer Anforderung
         * @description Alle Versionen, aelteste zuerst. Aus dem Vergleich aufeinanderfolgender Versionen ergeben sich alter Wert, neuer Wert und feldgenaue Herkunft (§16).
         */
        get: operations["RequirementsController_findVersions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRequirementDto: {
            dynamicAttributes?: {
                [key: string]: unknown;
            };
            /**
             * @description Bezeichner im Herkunftssystem. Zusammen mit sourceSystem eindeutig - eine Wiederholung wird mit 409 abgewiesen (Idempotenz nach §19.1).
             * @example A-4711
             */
            externalId?: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunft der Daten (§19.1). Ohne Angabe: eigene Erfassung.
             * @example sap
             */
            sourceSystem?: string;
            /**
             * @description Kein Vorgabewert: Ein fest verdrahteter Anfangszustand waere eine Workflow-Annahme, und §7 macht Zustaende konfigurierbar. Ab M4 liefert ihn die Workflow-Definition.
             * @example neu
             */
            status: string;
        };
        RequirementResponse: {
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** Format: uuid */
            id: string;
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        RequirementVersionResponse: {
            /** @description Client, der die Aenderung ausgefuehrt hat - aus dem Token. */
            changeSource: string;
            /** @description Ausloesende Identitaet. */
            changedBy: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Dynamische Attribute nach §6. Das gueltige Schema je Anforderungstyp wird zur Laufzeit ausgeliefert und ist hier bewusst nicht abgebildet. */
            dynamicAttributes: {
                [key: string]: unknown;
            };
            /** @description Bezeichner im Herkunftssystem. Leer bei eigener Erfassung. */
            externalId: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            operation: "insert" | "update" | "delete";
            owner: string;
            /** Format: uuid */
            projectId: string;
            /** @example feature */
            requirementType: string;
            /**
             * @description Herkunftssystem des Datensatzes (§19.1). Eigene Erfassung: infrademand.
             * @example infrademand
             */
            sourceSystem: string;
            /**
             * @description Interner Status. Noch nicht das stabile Statusvokabular des Integrationsvertrags nach CLAUDE.md §19.1 - die Abbildung folgt mit der Workflow-Engine in M4.
             * @example neu
             */
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            validFrom: string;
            /**
             * Format: date-time
             * @description Leer bei der aktuell gueltigen Version.
             */
            validTo: string | null;
            /** @example 1 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dienst ist bereit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    RequirementsController_findAll_v1: {
        parameters: {
            query?: {
                /** @description Stichtag. Ohne Angabe der aktuelle Bestand, mit Angabe der Zustand, den das System zu diesem Zeitpunkt kannte (§19.4). */
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bestand */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"][];
                };
            };
            /** @description Unlesbarer Stichtag */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequirementDto"];
            };
        };
        responses: {
            /** @description Angelegte Anforderung */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementResponse"];
                };
            };
            /** @description Rumpf unvollstaendig oder unbekannte Felder */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description sourceSystem und externalId existieren bereits (Idempotenz nach §19.1) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirementsController_findVersions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alle Versionen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementVersionResponse"][];
                };
            };
            /** @description Unlesbare Kennung */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein oder ungueltiges Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
